### ISSUE TITLE
bug(skin editor): category filtering stops if you type an non-existent category.

### ISSUE THREAD

**Issue by GabuTheDev** [cyperdark/osuck-skins#11]
### browser

Edge

### bug description

once you type a non-existent category (could also be a typo), the filtering stops and it does not display the available options anymore.

https://github.com/cyperdark/osuck-skins/assets/107962621/71967f1e-1dbf-4e2a-8de0-f8f4c09ec78a

**Comment by cyperdark** [comment]
fixed, plus now first searched item is selected
