### ISSUE TITLE
feat(skin dowload): check if user is focused on the window (& request to increase wait time).

### ISSUE THREAD

**Issue by GabuTheDev** [cyperdark/osuck-skins#12]
### feature description

Today I've noticed that the website does not check whenever the window is focused or not. The download countdown just runs in the background, which makes the whole waiting process useless.

The wait time was added in order to prevent users to mass-download skins using skins.
(they can still do it, but it's not as convenient)

I suggest to keep track on whenever the user has the specific window focused and only countdown when so.
(you can do this with `document.hasFocus()`)
I also suggest an wait time increase from 2 seconds (it's probably 3 seconds but page loading takes some time from it) up to 5 seconds.

**Comment by cyperdark** [comment]
fixed, i will stick with 2 seconds for now
