### ISSUE TITLE
feat(skin search): allow users to select multiple gamemodes. 

### ISSUE THREAD

**Issue by GabuTheDev** [cyperdark/osuck-skins#18]
### feature description

originally discussed [here](https://discord.com/channels/1056534107330445362/1061315256133091399).

users should be able to select multiple gamemodes to search for. Currently you can only select one at the time.

another idea would be to also add strict filter on double click, seaching only for skins with those specific gamemodes, no less, no more.

**Comment by cyperdark** [comment]
#21
