### ISSUE TITLE
feat(skin search): improve searching by adding keyword filtering & comparators.

### ISSUE THREAD

**Issue by GabuTheDev** [cyperdark/osuck-skins#20]
### feature description

As discussed, the next search keywords should be added:

### keywords with specific values
- [x] `creator:username` > useful to search for skins from specific creator
- [x] `publisher:username` > userful to search for skins from a specific publisher.
- [x] `HD:true/false` > search for skins with or without high quality assets
- [x] `SD:true/false` > search for skins with or without high quality assets
- [x] `animated:true/false` > search for skins with or without animated assets
- [x] `extra:true/false` > ..... with or without customization files
- [ ] `color:blue` > specific color search
- [x] `nsfw:true/false` > yeah.

### comparison operators
used with symbols such as: `>` `>=` `<` `<=` `=`

- [x] `downloads` > used with comparison.
- [x] `views` > used with comparison.
- [x] `rating` > used with comparison.

### logical operators
- [x] exclude skins (could use `-` or `!`): `-color:green` / `-minimalist` / `-rating:nsfw`

**Comment by cyperdark** [comment]
added source code of `sorting.js`
https://github.com/cyperdark/osuck-skins/blob/main/sorting.js
