### ISSUE TITLE
bug(*): Fix navbar position being wrong in mobile view.

### ISSUE THREAD

**Issue by GabuTheDev** [cyperdark/osuck-skins#22]
### browser

Chrome

### bug description

![image](https://github.com/cyperdark/osuck-skins/assets/107962621/19bf5d6e-07d1-4595-b8a5-b130d1a7db39)

**Comment by cyperdark** [comment]
![1703586296_qXUmeESTeg](https://github.com/cyperdark/osuck-skins/assets/21735205/a94f9e27-1d1c-4888-9f10-d85a819a64b8)
