### ISSUE TITLE
bug(skin.ini editor): preview area doesn't transit screens

### ISSUE THREAD

**Issue by expiteRz** [cyperdark/osuck-skins#24]
### browser

Firefox

### bug description

after all screens loaded, the preview area will not transit the screens even if clicking buttons whatever

https://github.com/cyperdark/osuck-skins/assets/51064411/b527a4bd-41bd-4695-a7b9-0eed77f14abb

**Comment by expiteRz** [comment]
also confirmed on edge and opera, and it happens on them

**Comment by GabuTheDev** [comment]
Does it only happen when switching from `song select` to anything else?

**Comment by expiteRz** [comment]
also happens when switching from `fruits` to anything else

hard to check _what if switching from `osu`_ because it already selected on page loaded

**Comment by cyperdark** [comment]
@expiteRz what about now?

**Comment by expiteRz** [comment]
it now fixed!
