### ISSUE TITLE
bug(download): inconsistent behavior on Gecko-based browsers.

### ISSUE THREAD

**Issue by LLLgin** [cyperdark/osuck-skins#26]
### bug description

Firefox and Waterfox: sometimes when you try to download skin (example:https://skins.osuck.net/skins/3519/download?v=1)
you get 406 error. F5 fix this

### New bug
 When I go to the skin page i got just interface on edge 
![изображение](https://github.com/cyperdark/osuck-skins/assets/83287515/0fa8052b-46ee-430d-a476-7c38e51e833e)
 Log: scrolling skins page -> press on skin -> got the problem

**Comment by cyperdark** [comment]
steps to replicate

**Comment by cyperdark** [comment]
And give proper title

**Comment by LLLgin** [comment]
> steps to replicate

just random

**Comment by cyperdark** [comment]
> > steps to replicate
> 
> just random

i need the exact steps to reproduce, otherwise i cant fix it

**Comment by LLLgin** [comment]
> > > steps to replicate
> > 
> > 
> > just random
> 
> i need the exact steps to reproduce, otherwise i cant fix it

Found any skin on osuck -> go to download page -> you the problem

**Comment by cyperdark** [comment]
> Found any skin on osuck -> go to download page -> you the problem

doesnt have issues

https://github.com/cyperdark/osuck-skins/assets/21735205/1ec67971-76d9-4d51-91c8-62ef85913f19

**Comment by LLLgin** [comment]
> > Found any skin on osuck -> go to download page -> you the problem
> 
> doesnt have issues
> 1708796955_xH5w8Y6u8p.mp4

Not always i say that before

**Comment by GabuTheDev** [comment]
Your issue description seems to have multiple bugs mentioned which do not really correlate with the main subject.
I do not understand anymore if this is an issue related to the download page or just the skin page not loading.
3 different browsers have been mentioned in the edited description, two gecko-based and one chromium-based.

Please fix your description so we can properly track and fix the issue you are facing.

**Comment by GabuTheDev** [comment]
We would also like to know which browser version you are using. Outdated browsers can also cause issues that can not be fixed by us.

**Comment by GabuTheDev** [comment]
Lately, I've also been experiencing this on the latest version of Chrome. From what I've seen, it has to do with JavaScript loader. Sometimes the browser decides to stop the loading process for no clear reason. (could be a framework issue; either Vue or Nuxt)

_NEEDS MORE INVESTIGATION._

**Comment by cyperdark** [comment]
fixed
