### ISSUE TITLE
bug(main page): Skin counters aren't being calculated on first website visit.

### ISSUE THREAD

**Issue by GabuTheDev** [cyperdark/osuck-skins#28]
### browser

Present on:
- Brave 1.65.114 (latest)
- Edge 124.0.2478.51 (latest beta)
- Chrome 24.0.6367.61 (latest)
- Opera GX LVL 5 (latest)

### bug description

https://github.com/cyperdark/osuck-skins/assets/107962621/f5759d9d-bd91-46e4-9738-914aacd7ef47

**Comment by cyperdark** [comment]
fixed in dev
