### ISSUE TITLE
bug():tosu issues

### ISSUE THREAD

**Issue by Rias-GremoryUwU** [cyperdark/osuck-skins#29]
### browser

Opera

### bug description

so i will try describe with the best of my ability so i followed the guide and followed all the videos but the first ever time i set it up it worked fine, when i turned off my computer didnt change any settings and logged back in everything stopped working i checked the debug logs any nothign, but i dont knowe whats going on i will have the yt vid linked showing what happened 
https://youtu.be/B47uofyvQoI

**Comment by GabuTheDev** [comment]
@Rias-GremoryUwU The video you linked is privated.

**Comment by Rias-GremoryUwU** [comment]
> @Rias-GremoryUwU The video you linked is privated.

sorry i will fix that

**Comment by Rias-GremoryUwU** [comment]
just made it public sorry about that

**Comment by cyperdark** [comment]
thats skins.osuck issues repo, post tosu issues in discord: https://discord.gg/WX7BTs8kwh
