### ISSUE TITLE
bug(main page): the new on-hover "gallery indicator" has visual bugs. 

### ISSUE THREAD

**Issue by GabuTheDev** [cyperdark/osuck-skins#8]
### browser

Edge

### bug description

I found some issues regarding the new on-hover "gallery indicator" while previewing today's new update.

### found issues
- the first image has the indicator always located at the top of the preview, while for the rest of the images, it is located at the bottom.
- even though an option to move the indication has been provided, it does not remember the option and continues to default to the bottom.
- the visuals have a slighly big delay, often not being rendered correctly if done at a fast pace.

### some solutions

- remove the position button, letting the user choose the location is not a great idea in terms of design and usability.
- the indicator should always be at the bottom, mostly because it completes the empty space (since there are already buttons at the top).
- the indicator and the hover button in top-right, both should have a slighly transparent background to allow visibility. (same applies for arrow buttons)
- both of the buttons should only be visible on hover, and fade out after not moving the cursor for a while. (same applies for arrow buttons)
- remove the drop shadow since it does not follow any design and looks kinda ugly.

https://github.com/cyperdark/osuck-skins/assets/107962621/b3471450-00be-4d3b-aa64-e973abe265b4

**Comment by GabuTheDev** [comment]
reviewing [the preview videos you've provided](https://discord.com/channels/1056534107330445362/1058262720274771968/1158217015346073720) it seems like the issues were not present on the dev branch.

**Comment by cyperdark** [comment]
fade animation of block removed, to reduce delay by 2-3x
removed choise
removed shadow
autopositiong bar based on picture id

**Comment by cyperdark** [comment]
> the indicator and the hover button in top-right, both should have a slighly transparent background to allow visibility. (same applies for arrow buttons)

this shit is invisible if i remove background
