### ISSUE TITLE
feat(skin editor): redirect to login modal instead of throwing error

### ISSUE THREAD

**Issue by GabuTheDev** [cyperdark/osuck-skins#9]
### feature description

when clicking on "new skin", it should redirect to the login page then to the skin editor instead of throwing an error.
![image](https://github.com/cyperdark/osuck-skins/assets/107962621/72c7fb08-de7f-4c34-944e-ca77377d0743)

**Comment by cyperdark** [comment]
oh yeah, were using it to prevent people to accedentaly see that button and go to this page, will fix later
